substitutions:
  _VERSION: "0.0.0-build."
  _NUGET_API: "https://api.nuget.org/v3/index.json"
  _NUGET_PUSH_KEY: "oy2nkpvkrxmkd3g6axdqhxzuzlxzreuebchf22q5ffvn7u"
  _PACKAGE_PATH: "/workspace/OnixCore/bin/Release/OnixCore"
  _TAG_COMMAND: "date -u +%Y%m%dT%H%M"

steps:

- name: 'ubuntu'
  args: ['bash', '-c', '${_TAG_COMMAND} > _TAG']

- name: 'gcr.io/its-artifact-commons/dotnet-sonar:2.2-4'
  entrypoint: 'bash'
  args: ['/workspace/GCloudBuild/sonar.bash']
  env: 
    - 'SONAR_KEY=${_SONAR_KEY}'
    - 'BUILT_VERSION=${_VERSION}'
    - 'BRANCH_NAME=${BRANCH_NAME}'
    - 'COMMIT_SHA=${COMMIT_SHA}'
    
- name: 'microsoft/dotnet:2.2-sdk' 
  entrypoint: 'dotnet'
  args:
    - build
    - OnixCore.sln 
    - -c
    - Release 
    - -p:Version=${_VERSION}${SHORT_SHA}

- name: 'microsoft/dotnet:2.2-sdk'
  entrypoint: 'dotnet'
  args:
    - nuget
    - push
    - ${_PACKAGE_PATH}.${_VERSION}${SHORT_SHA}.nupkg
    - -k
    - ${_NUGET_PUSH_KEY}
    - -s
    - ${_NUGET_API}

