substitutions:
  _VERSION: "0.0.0-build."
  _NUGET_API: "https://api.nuget.org/v3/index.json"
  _PACKAGE_PATH: "/workspace/OnixCore/bin/Release/OnixCore"

steps:
- name: 'gcr.io/its-artifact-commons/dotnet-sonar:2.2-4'
  entrypoint: 'bash'
  args: ['/workspace/GCloudBuild/sonar.bash']
  env: 
    - 'SONAR_KEY=${_SONAR_KEY}'
    - 'BUILT_VERSION=${_VERSION}${SHORT_SHA}'
    - 'BRANCH_NAME=${BRANCH_NAME}'
    - 'COMMIT_SHA=${COMMIT_SHA}'
    - 'BASELINE_VERSION=1.0.0'
    - 'ONIX_FIREBASE_BUCKET=${_ONIX_FIREBASE_BUCKET}'
    - 'ONIX_FIREBASE_DATABASE=${_ONIX_FIREBASE_DATABASE}'
    - 'ONIX_FIREBASE_KEY=${_ONIX_FIREBASE_KEY}'
    - 'ONIX_FIREBASE_USERNAME=${_ONIX_FIREBASE_USERNAME}'
    - 'ONIX_FIREBASE_PASSWORD=${_ONIX_FIREBASE_PASSWORD}'    
    - 'ONIX_SMTP_PASSWORD=${_ONIX_SMTP_PASSWORD}'    
    - 'ONIX_SMTP_HOST=${_ONIX_SMTP_HOST}'
    - 'ONIX_SMTP_USER=${_ONIX_SMTP_USER}'
    - 'ONIX_SMTP_PORT=${_ONIX_SMTP_PORT}'

- name: 'microsoft/dotnet:2.2-sdk' 
  entrypoint: 'dotnet'
  args:
    - build
    - OnixCore.sln 
    - -c
    - Release 
    - -p:Version=${_VERSION}${SHORT_SHA}

- name: 'microsoft/dotnet:2.2-sdk'
  entrypoint: 'dotnet'
  args:
    - nuget
    - push
    - ${_PACKAGE_PATH}.${_VERSION}${SHORT_SHA}.nupkg
    - -k
    - ${_NUGET_PUSH_KEY}
    - -s
    - ${_NUGET_API}

